//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTypeFilter
    {
        public int Property_ID { get; set; }
        public int Subcategory_ID { get; set; }
        public string Type_Name { get; set; }
        public string Type_Option { get; set; }
    
        public virtual tblProperty tblProperty { get; set; }
        public virtual tblSubcategory tblSubcategory { get; set; }
    }
}
